name: CI/CD Code

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.x'

      - name: Install dependencies
        run: npm i

      - name: Run lint
        run: npm run lint

      - name: Lint passes
        if: ${{ success() }}
        run: |
          echo "Lint pass correctly!!!"
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.x'

      - name: Install dependencies
        run: npm i

      - name: Run test
        run: npm run test

      - name: Test passes
        if: ${{ success() }}
        run: |
          echo "Test pass correctly!!!"
  deploy:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          echo "It is time to deploy!!!"
